config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'dashboard/admin_dashboard'
    get 'dashboard/projects_summery'
  end

  resources :projects do
    get :get_project_data
  end
  resources :todos
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'todos#index'
  # get 'projects/get_project_data', to: 'projects#get_project_data'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :projects
  has_many :todos

  DEVELOPER = 'Developer'
  ADMIN     = 'Admin'
  ROLES     = [DEVELOPER, ADMIN]

  def self.developers
    User.where(role: DEVELOPER)
  end

  def self.admin?(current_user)
    current_user.role == ADMIN
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def admin_dashboard
    @developers = User.developers
  end

  def projects_summery
    @projects = Project.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :role)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(user)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      # super
      case user.role
      when User::ADMIN
        users_dashboard_admin_dashboard_path
      when User::DEVELOPER
        todos_path
      else
        root_path
      end
    else
      stored_location_for(user) || request.referer || root_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/users/dashboard/admin_dashboard.html.erb
<div class="clear center">
	<h3>Developer's Summery</h3>
</div>

<div class="clear">
<table class="table table-striped center_text">
	<tbody>
		<!-- <td style="padding-top: 1%;" class="td_table_top">Status</td> -->
	<%# Todo::TODO_STATUSES.sort.each do |stat| %>
		<% @developers.each do |dev| %>
			<td class="td_table_top">
				<table>
					<td class="heading"><%= dev.email %></td>
					<% dev.todos.order(:status).each do |todo| %>
					<tr>
						<!-- <td><%#= todo.status %></td> -->
						<td><%= link_to todo.todo_name, todo_path(todo) %></td>
					</tr>
					<% end %>
				</table>
			</td>
		<% end %>
	<%# end %>
	<!-- <td style="padding-top: 1%;" class="td_table_top">Status</td> -->
	</tbody>
</table>
</div>

<div class="clear">
	<%= link_to 'Projects Summery', users_dashboard_projects_summery_path, class: 'btn btn-default' %>
	<%= link_to 'Projects', projects_path, class: 'btn btn-default' %>
</div>
<br/>

app/views/users/dashboard/projects_summery.html.erb
<div class="clear center">
	<h3>Projects Summery</h3>
</div>

<div class="clear">
<table class="table table-striped center_text">
	<tbody>
		<!-- <td style="padding-top: 1%;" class="td_table_top">Status</td> -->
	<%# Todo::TODO_STATUSES.sort.each do |stat| %>
		<% @projects.each do |proj| %>
			<td class="td_table_top">
				<table>
					<td class="heading"><%= link_to proj.project_name, project_path(proj) %></td>
					<% proj.todos.order(:status).each do |todo| %>
					<tr>
						<!-- <td><%#= todo.status %></td> -->
						<td><%= link_to todo.todo_name, todo_path(todo) %></td>
					</tr>
					<% end %>
				</table>
			</td>
		<% end %>
	<%# end %>
	<!-- <td style="padding-top: 1%;" class="td_table_top">Status</td> -->
	</tbody>
</table>
</div>

<div class="clear">
	<%= link_to 'Developers Status', users_dashboard_admin_dashboard_path, class: 'btn btn-default' %>
	<%= link_to 'Projects', projects_path, class: 'btn btn-default' %>
</div>
<br/>