config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'dashboard/admin_dashboard'
    get 'dashboard/projects_summery'
  end

  resources :projects do
    get :get_project_data
  end
  resources :todos
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'todos#index'
  # get 'projects/get_project_data', to: 'projects#get_project_data'
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :todos
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_project_data
    todos = Project.find(params[:project_id]).todos
    new_todos = todos.collect { |t| t if t.status == Todo::NEW }
    in_progress_todos = todos.collect { |t| t if t.status == Todo::IN_PROGRESS }
    completed_todos = todos.collect { |t| t if t.status == Todo::COMPLETED }
    json_array = [
                  ['Status', 'Total Todos'],
                  ['New', new_todos.compact.size],
                  ['In Progress', in_progress_todos.compact.size],
                  ['Completed', completed_todos.compact.size]
                ]
    render text: json_array
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= bootstrap_form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-lg-8 clearfix">
    <%#= f.label :project_name %>
    <%= f.text_field :project_name %>
  </div>

  <div class="actions col-lg-8 clearfix">
    <%= f.submit %>
    <%= link_to 'Back', projects_path, class: 'btn btn-default'  %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="clear center">
  <h3 class="center">Projects</h3>
</div>
<div class="clear">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Project name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete Project', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="clear">
<%= link_to 'New Project', new_project_path, class: 'btn btn-default' %>
<%= link_to 'New Todo', new_todo_path, class: 'btn btn-default' %>
<%= link_to 'Developers Status', users_dashboard_admin_dashboard_path, class: 'btn btn-default' %>
</div>
<br>

app/views/projects/new.html.erb
<h1>New Project</h1>
<div class="form-group">
<%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var jsonData = $.ajax({
          url: "<%= project_get_project_data_path(@project) %>",
          dataType: "json",
          async: false
          }).responseText;

        var data = google.visualization.arrayToDataTable(JSON.parse(jsonData));
        var options = {
          title: 'Project Summery'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>

<div class="well well-lg center_text">
<div class="clear">
  <strong>Project name:</strong>
  <%= @project.project_name %>
</div>
</div>

<div id="piechart" style="width: auto; height: auto;" ></div>

<div class="clear">
	<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-default' %>
	<%= link_to 'Back', projects_path, class: 'btn btn-default' %>
	<%= link_to 'Show Todos', todos_path(project: @project.id), class: 'btn btn-default' %>
</div>
<br/>