config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'dashboard/admin_dashboard'
    get 'dashboard/projects_summery'
  end

  resources :projects do
    get :get_project_data
  end
  resources :todos
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'todos#index'
  # get 'projects/get_project_data', to: 'projects#get_project_data'
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :project

  NEW = 'New'
  IN_PROGRESS = 'In Progress'
  COMPLETED = 'Completed'
  TODO_STATUSES = [NEW, IN_PROGRESS, COMPLETED]
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    # binding.pry
    @project = params[:project].present? ? Project.find(params[:project]) : nil
    @todos = @project.present? ? @project.todos : current_user.todos
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    @projects = Project.all.collect { |p| [ p.project_name, p.id ] }
    @developers = User.developers.collect { |d| [ d.email, d.id ] }
  end

  # GET /todos/1/edit
  def edit
    @projects = Project.all.collect { |p| [ p.project_name, p.id ] }
    @developers = User.developers.collect { |d| [ d.email, d.id ] }
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:todo_name, :project_id, :user_id, :status)
    end
end

app/views/todos/_form.html.erb
<%= bootstrap_form_for(todo) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="alert">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <% todo.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="field col-lg-8 clearfix">
    <%#= f.label :todo_name %>
    <%= f.text_field :todo_name %>
  </div>
  
  <div class="field col-lg-8 clearfix">
    <%#= f.label :project_id %>
    <%= f.select :project_id, @projects %>
  </div>

  <div class="field col-lg-8 clearfix">
    <%#= f.label :user_id %>
    <%= f.select :user_id, @developers %>
  </div>

  <div class="field col-lg-8 clearfix">
    <%#= f.label :status %>
    <%= f.select :status, Todo::TODO_STATUSES %>
  </div>

  <div class="actions col-lg-8 clearfix">
    <%= f.submit %>
    <%= link_to 'Back', todos_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div class="clear center">
  <h3 class="center">Todos</h3>
</div>
<div class="clear">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Todo name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.todo_name %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Delete Todo', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="clear">
<% if User.admin?(current_user) %>
  <%= link_to 'New Todo', new_todo_path, class: 'btn btn-default' %>
  <%= link_to 'Projects', projects_path, class: 'btn btn-default' %>
<% end %>
</div>
<br>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<div class="form-group">
<%= render 'form', todo: @todo %>
</div>

app/views/todos/show.html.erb
<div class="well well-lg center_text">
<div class="clear">
  <strong>Todo name:</strong>
  <%= @todo.todo_name %>
</div>

<div class="clear">
  <strong>Project name:</strong>
  <%= @todo.project.project_name %>
</div>

<div class="clear">
  <strong>Developer:</strong>
  <%= @todo.user.email %>
</div>

<div class="clear">
  <strong>Status:</strong>
  <%= @todo.status.blank? ? 'New' : @todo.status %>
</div>

<div class="clear">
	<%= link_to 'Edit', edit_todo_path(@todo), class: 'btn btn-default'  %>
	<%= link_to 'Back', todos_path, class: 'btn btn-default'  %>
</div>
</div>
<br/>