config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'dashboard/admin_dashboard'
    get 'dashboard/projects_summery'
  end

  resources :projects do
    get :get_project_data
  end
  resources :todos
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'todos#index'
  # get 'projects/get_project_data', to: 'projects#get_project_data'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Todos Management</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>

  <body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <a class="navbar-brand" href="<% root_path %>">Project Todos Management</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="<%= edit_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Welcome <%= current_user.email %></a></li>
            <li><a href="<%= destroy_user_session_path %>" data-method='delete' ><span class="glyphicon glyphicon-log-out"></span> Sign out</a></li>
          <% else %>
            <li><a href=" <%= new_registration_path(resource_name) %> "><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="<%= new_session_path(resource_name) %>" ><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div>
    <div id="notice" class="notice"><%= notice %></div>
    <div id="error" class="alert"><%= alert %></div>
    <div class="center_div">
      <%= yield %>
    </div>
  </div>
  </body>
</html>